#server:
#  port: 8081

spring:
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  datasource: 
    mybaties: 
      enabled: true
      type: com.alibaba.druid.pool.DruidDataSource  
      
      driverClassName: com.mysql.jdbc.Driver
      
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

security:
  basic:
    enabled: false 
    
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.com.niub.domain
  check-config-location: true
  
#pagehelper分页插件
pagehelper:
    #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
    helperDialect: mysql
    #分页合理化参数，默认值为false。
    #当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。
    #默认false 时，直接根据参数进行查询。
    reasonable: true
    #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，
    #自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
    supportMethodsArguments: true
    
    params: count=countSql